//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexParserTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApexParserTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global with sharing class MethodOne
        ///{
        ///    void StringVoid()
        ///    {
        ///    }
        ///
        ///    public void StringPublic()
        ///    {
        ///    }
        ///
        ///    string GetString()
        ///    {
        ///        return &apos;Hello World&apos;;
        ///    }
        ///
        ///    public string GetStringPublic()
        ///    {
        ///        return &apos;Hello World&apos;;
        ///    }
        ///
        ///    private string GetStringprivate()
        ///    {
        ///        return &apos;Hello World&apos;;
        ///    }
        ///
        ///    global string GetStringglobal()
        ///    {
        ///        return &apos;Hello World&apos;;
        ///    }
        ///
        ///    List&lt;string&gt; GetGenericList()
        ///    {
        ///        return new List&lt;string&gt;();
        ///    }
        ///
        ///    Map&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodsOne {
            get {
                return ResourceManager.GetString("MethodsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @isTest
        ///public with sharing class MethodTwo
        ///{
        ///    @isTest public static void TestMethodOne()
        ///    {
        ///        System.debug(&apos;TestMethodOne&apos;);
        ///    }
        ///
        ///    @isTest static void TestMethodThree()
        ///    {
        ///        System.debug(&apos;TestMethodThree&apos;);
        ///    }
        ///
        ///    // Does Not Work
        ///    static testMethod void TestMethodFour()
        ///    {
        ///        System.debug(&apos;TestMethodFour&apos;);
        ///    }
        ///
        ///    public testMethod static void TestMethodTwo()
        ///    {
        ///        System.debug(&apos;TestMethodTwo&apos;);
        ///    }
        ///}.
        /// </summary>
        internal static string MethodsTwo {
            get {
                return ResourceManager.GetString("MethodsTwo", resourceCulture);
            }
        }
    }
}
