public class ComJayProjectUtilApexclassname
{
    // Class
    ComJayProjectUtilApexclassname()
    {

    }

    // Class Word Open Close
    void Demo()
    {
        Account abcString = new Account();
        DemoTwo(new ComJayProjectUtilApexclassname());
    }


    // Class Word Open Class Word Comma Class Word Close
    void DemeTwo(Account acc, String accString)
    {

    }

    // Class Word Open Class Word Close
    void DemeTwo(Account acc)
    {

    }

    // Class Word Open Close Curly
    String DemoTwo()
    {
        DemoTwo(new ComJayProjectUtilApexclassname());
        return 'OK';
    }

    String DemoTwo(ComJayProjectUtilApexclassname demo)
    {
        return 'OK';
    }

    class DemoTwo{

    }
}