//::    ApexClassDeclarationSyntax
public without sharing class FieldPropertyExpression {
//::    ApexMethodDeclarationSyntax
public void MethodOne() {
//::    ApexFieldDeclarationSyntax
DateTime dateTimeEmpty;
//::    ApexExpressionStatementSyntax
dateTimeEmpty = DateTime.now();
//::    ApexFieldDeclarationSyntax
DateTime dateTimeInitilized = DateTime.now();
//::    ApexFieldDeclarationSyntax
List<DateTime> dateTimeList = new List<DateTime>();
//::    ApexFieldDeclarationSyntax
DateTime[] dateTimeArrary = new DateTime[5];
//::    ApexExpressionStatementSyntax
System.debug('Hello World');
    String Name;
    Name = 'Jay';
//::    CloseBrace
}
//::    CloseBrace
}